### ISSUE TITLE
Mostrar listado de ropa (Hito - 20 de abril)

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-twq103-vintage-clothes#2]
Hola:

Os comento lo que veo de vuestra primera entrega y os propongo el desarrollo de más funcionalidad.

El menú es bastante básico y está incompleto para las opciones ya que no contempla requisitos que habéis redactado. Además, deberíais hacerlo para que el menú se repita indefinidamente.

Debéis describir en el archivo principal los "Objetivos del trabajo" con la descripción más detallada de cada una de las funcionalidades. No me quedan claras.

El hito que os propongo para el 20 de abril es que creéis un fichero con todas las prendas que se pueden comprar, unidades disponibles y sus precios y sean los que se muestren en la opción correspondiente del menú. Os aconsejo que almacenéis los datos en un vector de estructuras.

Además de esto, os animo a que sigáis programando más funcionalidades.

Un saludo y buenas vacaciones.

**Comment by avdlp11** [comment]
Ya hemos mejorado el programa
